rails_guides/blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles

  root 'welcome#index'
end

rails_guides/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_guides/blog/app/models/article.rb
class Article < ApplicationRecord
end

rails_guides/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_guides/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def index
        # list ALL articles
        @articles = Article.all
    end

    def show
        # display!
        @article = Article.find(params[:id])
    end

    def new
        # new article action
    end

    def create
        ### inital way to see what's going on (not super-useful)     
        #render plain: params[:article].inspect

        ### UNSAFE - yields security error:
        #@article = Article.new(params[:article])
        
        ### SAFE - but better refactored out into the below private method
        #@article = Article.new(params.require(:article).permit(:title, :text))

        @article = Article.new(article_params)

        @article.save
        redirect_to @article
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

rails_guides/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails_guides/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_guides/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails_guides/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails_guides/blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New_Article', new_article_path %>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th></th>
    </tr>

    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
        </tr>
    <% end %>    
</table>

rails_guides/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

<%= link_to 'Back', articles_path %>

rails_guides/blog/app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

rails_guides/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_guides/blog/app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<%= link_to 'My Blog', controller: 'articles'  %>